from pathlib import Path

import pytest
import yaml

from mobipick_gui.workspaces import RosWorkspace, WorkspaceRegistry


def test_create_save_and_reload_workspace_registry(tmp_path):
    registry_path = tmp_path / 'config' / 'workspaces.yaml'
    master = tmp_path / 'ros1_ws'
    registry = WorkspaceRegistry(registry_path)
    registry.master_folder = str(master)

    base = registry.create('base_ws')
    child = registry.create('child_ws', extends=['base_ws'])
    child.image = 'example/child:latest'
    registry.upsert(child)
    registry.active = child.name
    registry.save()

    assert (base.directory / 'src').is_dir()
    assert (child.directory / 'src').is_dir()
    assert not child.is_built

    loaded = WorkspaceRegistry(registry_path).load()
    assert loaded.active == 'child_ws'
    assert loaded.get('child_ws').extends == ['base_ws']
    assert loaded.get('child_ws').image == 'example/child:latest'


def test_runtime_environment_mounts_master_at_canonical_ros_ws(tmp_path):
    master = tmp_path / 'ros1_ws'
    container_root = Path('/home/test/ros_ws')
    workspace = master / 'demo_ws'
    (workspace / 'src').mkdir(parents=True)
    registry = WorkspaceRegistry(
        tmp_path / 'workspaces.yaml',
        container_workspace_root=container_root,
    )
    registry.master_folder = str(master)
    registry.upsert(RosWorkspace(name='demo_ws', path=str(workspace)))
    registry.active = 'demo_ws'

    environment = registry.runtime_environment(
        empty_mount_source=tmp_path / 'empty'
    )

    assert environment['MOBIPICK_WORKSPACE_ENABLED'] == '1'
    assert environment['MOBIPICK_WORKSPACE_MOUNT_SOURCE'] == str(master)
    assert environment['MOBIPICK_WORKSPACE_MOUNT_TARGET'] == str(
        container_root
    )
    assert environment['MOBIPICK_WORKSPACE_SETUP'] == str(
        container_root / 'demo_ws' / 'devel' / 'setup.bash'
    )
    assert environment['MOBIPICK_WORKSPACE_DEVEL_PATHS'] == str(
        container_root / 'demo_ws' / 'devel'
    )
    assert environment['MOBIPICK_WORKSPACE_COMPAT_ROOTS'] == str(master)
    assert environment['MOBIPICK_WORKSPACE_BUILT'] == '0'
    assert environment['ROS_WORKSPACE'] == str(
        container_root / 'demo_ws' / 'src'
    )
    assert environment['MOBIPICK_ROS_PACKAGE_PATH'] == str(
        container_root / 'demo_ws' / 'src'
    )


def test_image_default_uses_empty_mount(tmp_path):
    empty = tmp_path / 'empty'
    empty.mkdir()
    registry = WorkspaceRegistry(tmp_path / 'workspaces.yaml')

    environment = registry.runtime_environment(empty_mount_source=empty)

    assert environment['MOBIPICK_WORKSPACE_ENABLED'] == '0'
    assert environment['MOBIPICK_WORKSPACE_MOUNT_SOURCE'] == str(empty)
    assert environment['MOBIPICK_WORKSPACE_MOUNT_TARGET'].startswith('/tmp/')
    assert environment['MOBIPICK_WORKSPACE_COMPAT_ROOTS'] == ''
    assert environment['MOBIPICK_ROS_PACKAGE_PATH'] == ''
    assert environment['ROS_WORKSPACE'] == ''


def test_runtime_environment_exposes_overlay_source_paths(tmp_path):
    master = tmp_path / 'ros1_ws'
    container_root = Path('/home/test/ros_ws')
    base = RosWorkspace(name='base_ws', path=str(master / 'base_ws'))
    overlay = RosWorkspace(
        name='overlay_ws',
        path=str(master / 'overlay_ws'),
        extends=['base_ws'],
    )
    registry = WorkspaceRegistry(
        tmp_path / 'workspaces.yaml',
        container_workspace_root=container_root,
    )
    registry.master_folder = str(master)
    registry.upsert(base)
    registry.upsert(overlay)
    registry.active = overlay.name

    environment = registry.runtime_environment(
        empty_mount_source=tmp_path / 'empty'
    )

    assert environment['MOBIPICK_ROS_PACKAGE_PATH'].split(':') == [
        str(container_root / 'overlay_ws' / 'src'),
        str(container_root / 'base_ws' / 'src'),
    ]
    assert environment['MOBIPICK_WORKSPACE_DEVEL_PATHS'].split(':') == [
        str(container_root / 'base_ws' / 'devel'),
        str(container_root / 'overlay_ws' / 'devel'),
    ]


def test_empty_setup_file_is_not_treated_as_built(tmp_path):
    workspace = RosWorkspace(name='demo', path=str(tmp_path / 'demo'))
    workspace.setup_file.parent.mkdir(parents=True)
    workspace.setup_file.touch()

    assert not workspace.is_built

    workspace.setup_file.write_text('# generated by catkin\n', encoding='utf-8')
    assert workspace.is_built


def test_runtime_build_accepts_setup_sh_fallback(tmp_path):
    workspace = RosWorkspace(name='demo', path=str(tmp_path / 'demo'))
    workspace.setup_file.parent.mkdir(parents=True)
    workspace.setup_file.touch()
    setup_sh = workspace.setup_file.with_name('setup.sh')
    setup_sh.write_text('# generated by catkin\n', encoding='utf-8')
    registry = WorkspaceRegistry(tmp_path / 'workspaces.yaml')

    assert registry.is_runtime_built(workspace)


def test_built_overlay_adds_catkin_package_paths_not_source_root(tmp_path):
    container_root = Path('/home/test/ros_ws')
    base = RosWorkspace(name='base', path=str(tmp_path / 'base'))
    overlay = RosWorkspace(
        name='overlay',
        path=str(tmp_path / 'overlay'),
        extends=['base'],
    )
    for workspace in (base, overlay):
        setup_sh = workspace.directory / 'devel' / 'setup.sh'
        setup_sh.parent.mkdir(parents=True)
        setup_sh.write_text('# generated by catkin\n', encoding='utf-8')
    overlay_packages = [
        overlay.directory / 'src' / 'first_package',
        overlay.directory / 'src' / 'nested' / 'second_package',
    ]
    (overlay.directory / 'devel' / '.catkin').write_text(
        ';'.join(str(path) for path in overlay_packages),
        encoding='utf-8',
    )
    registry = WorkspaceRegistry(
        tmp_path / 'workspaces.yaml',
        container_workspace_root=container_root,
    )
    registry.upsert(base)
    registry.upsert(overlay)
    registry.active = overlay.name

    environment = registry.runtime_environment(
        empty_mount_source=tmp_path / 'empty'
    )

    assert environment['MOBIPICK_ROS_PACKAGE_PATH'].split(':') == [
        str(container_root / 'overlay' / 'src' / 'first_package'),
        str(
            container_root
            / 'overlay'
            / 'src'
            / 'nested'
            / 'second_package'
        ),
    ]
    assert str(container_root / 'overlay' / 'src') not in (
        environment['MOBIPICK_ROS_PACKAGE_PATH'].split(':')
    )


def test_registry_rejects_inheritance_cycles(tmp_path):
    registry = WorkspaceRegistry(tmp_path / 'workspaces.yaml')
    registry.upsert(RosWorkspace(name='first', path=str(tmp_path / 'first')))
    registry.upsert(
        RosWorkspace(
            name='second',
            path=str(tmp_path / 'second'),
            extends=['first'],
        )
    )

    with pytest.raises(ValueError, match='cycle'):
        registry.upsert(
            RosWorkspace(
                name='first',
                path=str(tmp_path / 'first'),
                extends=['second'],
            )
        )


def test_graph_marks_active_workspace_and_edges(tmp_path):
    registry = WorkspaceRegistry(tmp_path / 'workspaces.yaml')
    registry.upsert(RosWorkspace(name='base', path=str(tmp_path / 'base')))
    registry.upsert(
        RosWorkspace(
            name='child',
            path=str(tmp_path / 'child'),
            extends=['base'],
        )
    )
    registry.active = 'child'

    dot = registry.graph_dot()

    assert '"base" -> "child"' in dot
    assert 'fillcolor="#b7e4c7"' in dot


def test_build_command_builds_missing_underlays_in_order(tmp_path):
    registry = WorkspaceRegistry(tmp_path / 'workspaces.yaml')
    clean = RosWorkspace(name='clean', path=str(tmp_path / 'clean'))
    common = RosWorkspace(
        name='common',
        path=str(tmp_path / 'common'),
        extends=['clean'],
    )
    gpt = RosWorkspace(
        name='gpt',
        path=str(tmp_path / 'gpt'),
        extends=['common'],
    )
    registry.upsert(clean)
    registry.upsert(common)
    registry.upsert(gpt)

    command = registry.build_command(gpt)

    clean_index = command.index(str(clean.directory))
    common_index = command.index(str(common.directory))
    gpt_index = command.index(str(gpt.directory))
    assert clean_index < common_index < gpt_index
    assert command.count('catkin build') == 3


def test_runtime_environment_maps_relocated_catkin_build(tmp_path):
    current_root = tmp_path / 'ros1_ws'
    old_root = tmp_path / 'ros_ws'
    container_root = Path('/home/test/ros_ws')
    base_dir = current_root / 'base_ws'
    base_setup = base_dir / 'devel' / 'setup.sh'
    base_setup.parent.mkdir(parents=True)
    base_setup.write_text('# generated\n', encoding='utf-8')
    workspace_dir = current_root / 'gpt_ws'
    generated_setup = (
        workspace_dir
        / 'devel'
        / '.private'
        / 'catkin_tools_prebuild'
        / 'setup.bash'
    )
    generated_setup.parent.mkdir(parents=True)
    generated_setup.write_text('# generated\n', encoding='utf-8')
    (workspace_dir / 'devel' / '.catkin').write_text(
        str(old_root / 'gpt_ws' / 'src' / 'mobipick_gpt'),
        encoding='utf-8',
    )
    public_setup = workspace_dir / 'devel' / 'setup.bash'
    public_setup.symlink_to(
        old_root
        / 'gpt_ws'
        / 'devel'
        / '.private'
        / 'catkin_tools_prebuild'
        / 'setup.bash'
    )
    registry = WorkspaceRegistry(
        tmp_path / 'workspaces.yaml',
        container_workspace_root=container_root,
    )
    registry.master_folder = str(current_root)
    registry.upsert(RosWorkspace(name='base_ws', path=str(base_dir)))
    registry.upsert(
        RosWorkspace(
            name='gpt_ws',
            path=str(workspace_dir),
            extends=['base_ws'],
        )
    )
    registry.active = 'gpt_ws'

    environment = registry.runtime_environment(
        empty_mount_source=tmp_path / 'empty'
    )

    assert environment['MOBIPICK_WORKSPACE_MOUNT_SOURCE'] == str(current_root)
    assert environment['MOBIPICK_WORKSPACE_MOUNT_TARGET'] == str(
        container_root
    )
    assert environment['MOBIPICK_WORKSPACE_COMPAT_ROOTS'].split(':') == [
        str(current_root),
        str(old_root),
    ]
    assert environment['ROS_WORKSPACE'] == str(
        container_root / 'gpt_ws' / 'src'
    )
    assert environment['MOBIPICK_ROS_PACKAGE_PATH'] == str(
        container_root / 'gpt_ws' / 'src' / 'mobipick_gpt'
    )
    assert registry.is_runtime_built(registry.get('gpt_ws'))


def test_legacy_selector_migrates_active_workspace_and_profiles(
    tmp_path,
    monkeypatch,
):
    home = tmp_path / 'home'
    monkeypatch.setenv('HOME', str(home))
    resources = tmp_path / 'resources'
    private = resources / 'private'
    buttons = private / 'button_configs'
    experiments = private / 'experiments'
    buttons.mkdir(parents=True)
    experiments.mkdir()
    (home / 'ros1_ws' / 'base_ws' / 'src').mkdir(parents=True)
    (home / 'ros1_ws' / 'child_ws' / 'src').mkdir(parents=True)
    (buttons / 'button_commands_child_ws.yaml').write_text(
        'buttons: []\n',
        encoding='utf-8',
    )
    (experiments / 'child_ws_experiments.yaml').write_text(
        'timeline: []\n',
        encoding='utf-8',
    )
    (private / 'config.yml').write_text(
        yaml.safe_dump(
            {
                'commands': {
                    'child_ws': ['roslaunch', 'demo', 'demo.launch']
                }
            }
        ),
        encoding='utf-8',
    )
    (private / 'select_ros1_ws.sh').write_text(
        '''
DESIRED_NUMBER=1
rws_list=(
    $HOME/ros_ws/base_ws/src # base
    $HOME/ros_ws/child_ws/src # extends #0
)
''',
        encoding='utf-8',
    )

    registry = WorkspaceRegistry(
        tmp_path / 'registry.yaml',
        resources_root=resources,
    ).load()

    child = registry.get('child_ws')
    assert registry.active == 'child_ws'
    assert child.extends == ['base_ws']
    assert child.button_config.endswith('button_commands_child_ws.yaml')
    assert child.launch_config.endswith('child_ws_experiments.yaml')
    assert child.sim_command == 'roslaunch demo demo.launch'


def test_known_workspaces_infer_their_docker_images(tmp_path):
    registry = WorkspaceRegistry(
        tmp_path / 'workspaces.yaml',
        resources_root=tmp_path,
    )

    gpt = registry.with_inferred_profile(
        RosWorkspace(name='gpt_ws', path=str(tmp_path / 'gpt_ws'))
    )
    rae = registry.with_inferred_profile(
        RosWorkspace(
            name='rae_upom_mobipick_ws',
            path=str(tmp_path / 'rae_upom_mobipick_ws'),
        )
    )

    assert gpt.image == (
        'ozkrelo/x_mobipick_labs:gpt_ws_from_oscar_user'
    )
    assert rae.image == (
        'ozkrelo/x_mobipick_labs:rae_ws_from_oscar_user'
    )


def test_workspace_image_falls_back_to_gui_default(tmp_path):
    registry = WorkspaceRegistry(tmp_path / 'workspaces.yaml')
    registry.upsert(
        RosWorkspace(name='demo_ws', path=str(tmp_path / 'demo_ws'))
    )

    assert registry.image_for('demo_ws', 'example/default:latest') == (
        'example/default:latest'
    )
