services:
  mobipick:
    hostname: mobipick
    # gazebo server
    image: ${MOBIPICK_IMAGE:-ozkrelo/mobipick_labs:noetic}
    working_dir: ${HOME}/ros_ws/
    entrypoint: /usr/local/bin/entrypoint_user.sh
    user: "${USER}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - DISPLAY # for Gazebo GUI
      - "ROS_DISTRO=noetic"
      - "GAZEBO_MASTER_URI=http://mobipick:12345"
      - "ROS_MASTER_URI=http://mobipick:11311"
      - "ROS_HOSTNAME=mobipick"
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
      - XDG_RUNTIME_DIR
      - __NV_PRIME_RENDER_OFFLOAD
      - __GLX_VENDOR_LIBRARY_NAME
      - DISABLE_ROS1_EOL_WARNINGS=1
      # - ROS_WORKSPACE=${HOME}/{{ros1_workspace}}/src
      # - HOST_USER=${USER}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # for Gazebo GUI
      - /run/user:/run/user:rw  # for Gazebo GUI
      - ./scripts:/scripts_430ofkjl04fsw:rw
      # uncomment to add custom entrypoint script
      - ./custom_entrypoint.sh:/usr/local/bin/entrypoint_user.sh:ro
      - ./private/select_ros1_ws.sh:${HOME}/scripts/personal_config/select_ros1_ws.sh:ro
      - ~/ros1_ws:${HOME}/ros_ws:rw
    expose:
      - 11311 # roscore
      - 12345 # gzserver
    privileged: true  # for Gazebo GUI
    command: {{ command }}
    networks:
      default:
        aliases:
          - mobipick

  mobipick_cmd:
    # hostname: mobipick # from mobipick service above
    # gazebo server
    image: ${MOBIPICK_IMAGE:-ozkrelo/mobipick_labs:noetic}
    # image: ${MOBIPICK_IMAGE:-ozkrelo/x_mobipick_labs:oscar_user_from_1.2}
    working_dir: ${HOME}/ros_ws/
    entrypoint: /usr/local/bin/entrypoint_user.sh
    # user: "${USER}" # from mobipick service above
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - DISPLAY # for Gazebo GUI
      - "ROS_DISTRO=noetic"
      - "GAZEBO_MASTER_URI=http://mobipick:12345"
      - "ROS_MASTER_URI=http://mobipick-roscore:11311"
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
      - XDG_RUNTIME_DIR
      - __NV_PRIME_RENDER_OFFLOAD
      - __GLX_VENDOR_LIBRARY_NAME
      - DISABLE_ROS1_EOL_WARNINGS=1
      # - HOST_USER=${USER} # from mobipick service above
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # for gazebo gui
      - /run/user:/run/user:rw  # for Gazebo GUI
      - ./scripts:/scripts_430ofkjl04fsw:rw
      # uncomment to add custom entrypoint script
      - ./custom_entrypoint.sh:/usr/local/bin/entrypoint_user.sh:ro
      - ./private/select_ros1_ws.sh:${HOME}/scripts/personal_config/select_ros1_ws.sh:ro
      - ~/ros1_ws:${HOME}/ros_ws:rw
      - ~/.ssh:${HOME}/.ssh:rw # for git access
    privileged: true  # for Gazebo GUI

networks:
  default:
    name: mobipick
    external: true
